include StarlingMonkey build for release (#815)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -324,7 +324,7 @@ jobs:
   test-npm-package:
     if: github.ref != 'refs/heads/main'
     runs-on: ubuntu-latest
-    needs: [build]
+    needs: [build, starlingmonkey-build]
     strategy:
       matrix:
         node-version: [18, 20]
@@ -338,6 +338,10 @@ jobs:
       uses: actions/download-artifact@v3
       with:
         name: engine-release
+    - name: Download Engine
+      uses: actions/download-artifact@v3
+      with:
+        name: starling-release
     - run: yarn
       shell: bash
     - run: npm test
@@ -356,3 +360,127 @@ jobs:
         fastly-api-token: ${{ secrets.FASTLY_API_TOKEN }}
         fastly-cli-version: ${{ env.fastly-cli_version }}
         github-token: ${{ secrets.GITHUB_TOKEN }}
+
+  starlingmonkey-build:
+    name: StarlingMonkey Build
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        submodules: true
+    - name: Install Rust 1.77.1
+      run: |
+        rustup toolchain install 1.77.1
+        rustup target add wasm32-wasi --toolchain 1.77.1
+    - name: Build
+      run: npm run build:starlingmonkey
+    - uses: actions/upload-artifact@v3
+      with:
+        name: starling-release
+        path: starling.wasm
+
+  starlingmonkey-run_wpt:
+    if: github.ref != 'refs/heads/main'
+    name: Run Web Platform Tests
+    needs: [starlingmonkey-build, ensure_cargo_installs]
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        submodules: true
+    - uses: actions/setup-node@v3
+      with:
+        node-version: 20
+        cache: 'yarn'
+
+    - name: Download Engine
+      uses: actions/download-artifact@v3
+      with:
+        name: starling-release
+
+    - name: Restore Viceroy from cache
+      uses: actions/cache@v3
+      with:
+        path: "/home/runner/.cargo/bin/viceroy"
+        key: crate-cache-viceroy-${{ env.viceroy_version }}
+    
+    - name: Restore wasm-tools from cache
+      uses: actions/cache@v3
+      id: wasm-tools
+      with:
+        path: "/home/runner/.cargo/bin/wasm-tools"
+        key: crate-cache-wasm-tools-${{ env.wasm-tools_version }}
+    
+    - name: "Check wasm-tools has been restored"
+      if: steps.wasm-tools.outputs.cache-hit != 'true'
+      run: |
+        echo "wasm-tools was not restored from the cache"
+        echo "bailing out from the build early"
+        exit 1
+    
+    - run: yarn install --frozen-lockfile
+
+    - name: Build WPT runtime
+      run: tests/wpt-harness/build-wpt-runtime.sh --starlingmonkey
+
+    - name: Prepare WPT hosts
+      run: |
+        cd tests/wpt-harness/wpt
+        ./wpt make-hosts-file | sudo tee -a /etc/hosts
+
+    - name: Run tests
+      timeout-minutes: 20
+      run: node ./tests/wpt-harness/run-wpt.mjs --starlingmonkey -vv
+
+  starlingmonkey-sdktest:
+    if: github.ref != 'refs/heads/main'
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        platform: [viceroy, compute]
+    needs: [starlingmonkey-build]
+    steps:
+    - name: Checkout fastly/js-compute-runtime
+      uses: actions/checkout@v3
+    - uses: actions/setup-node@v3
+      with:
+        node-version: 'lts/*'
+        cache: 'yarn'
+
+    - name: Set up Fastly CLI
+      uses: fastly/compute-actions/setup@v4
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
+        cli_version: ${{ env.fastly-cli_version }}
+
+    - name: Restore Viceroy from cache
+      if: ${{ matrix.platform == 'viceroy' }}
+      uses: actions/cache@v3
+      id: viceroy
+      with:
+        path: "/home/runner/.cargo/bin/viceroy"
+        key: crate-cache-viceroy-${{ env.viceroy_version }}
+    
+    - name: Restore wasm-tools from cache
+      uses: actions/cache@v3
+      id: wasm-tools
+      with:
+        path: "/home/runner/.cargo/bin/wasm-tools"
+        key: crate-cache-wasm-tools-${{ env.wasm-tools_version }}
+
+    - name: "Check caches have been restored"
+      if: steps.wasm-tools.outputs.cache-hit != 'true' || matrix.platform == 'viceory' && steps.viceroy.outputs.cache-hit != 'true'
+      run: echo "Unable to restore from the cache, bailing." && exit 1
+
+    - name: Download Engine
+      uses: actions/download-artifact@v3
+      with:
+        name: starling-release
+    - run: yarn install --frozen-lockfile
+
+    - name: Yarn install
+      run: yarn && cd ./integration-tests/js-compute && yarn
+
+    - run: node integration-tests/js-compute/test.js --starlingmonkey ${{ matrix.platform == 'viceroy' && '--local' || '' }}
+      env:
+        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
